### ISSUE TITLE
Photo / Slideshow issue

### ISSUE THREAD

**Issue by sollenne** [mdchappe/kronosource#1]
VIEW PROPERTY & VIEW UNIT 

How are we going to do the pictures? If we need to do a slideshow, We need to move fast on that. (Flexslider is a UL and we can dynamically inject "li"'s into it.)

**Comment by kodehammer** [comment]
@sollenne I don't think we'll start with a slideshow, more like a thumbnail gallery.  I don't know if i'm going to get to adding this in before Sunday night - it depends on how the unit search query goes.

**Comment by sollenne** [comment]
assigning to me for 2.0, if that ever happens
