### ISSUE TITLE
alert after sent message

### ISSUE THREAD

**Issue by sollenne** [mdchappe/kronosource#11]
For the most part it's fine, but if you choose to "send message" from the "view property" or "view unit"  pages, it takes you to the "compose message" page. If you "discard draft" it will take you back to where you came from, but if you choose to "send message", it will take you back to your inbox. Can we get it to go back to the page you were on before?

**Comment by kodehammer** [comment]
Yeah, should be able to do this.  It will be lower priority than completing the missing functionality, but I have a good idea of how to make it work.

**Comment by sollenne** [comment]
in lieu of taking you back where you came from, we can just have a little $status alert like other pages have after an action is complete. Changing to bug unless we decide that it won't make this release.

**Comment by kodehammer** [comment]
I did both.

**Comment by sollenne** [comment]
I don't see this working Do i need to update db or something? @owtytrof

**Comment by kodehammer** [comment]
No, I screwed something up last night.  I had to do some testing on the server last night for functions that send emails, and at some point accidentally overwrote some changes.  Should be working if you pull my latest update.
