### ISSUE TITLE
Units - update add, edit, and view to reflect DB changes

### ISSUE THREAD

**Issue by kodehammer** [mdchappe/kronosource#13]
In order to be properly searchable, had to change some database fields from varchar to int, and date field from date to int to conform with other dates being stored in the db.  Need to update methods to work with the new field types as well as update views to specify units(months, $, etc).

**Comment by sollenne** [comment]
Do I need to change something in my local setup to see these changes?

**Comment by kodehammer** [comment]
When it's all set I'll update the local db zip.  I'm not sure if/how to import only the table changes without the affecting any data you've added/changed in your local copy, though.

**Comment by kodehammer** [comment]
Committed fix tonight.
