### ISSUE TITLE
pet policy > locator/viewProperty

### ISSUE THREAD

**Issue by sollenne** [mdchappe/kronosource#27]
there are still 'pet deposit' and 'pet rent' inputs on the terms area. I think Armando said we should delete those. I know pet policy is covered under 'property features', but since pet policies are more in depth, can we break it into it's own 'row'? 

Also, we need to make it so that IF they have a pet policy, display it, otherwise hide. Really the same thing goes for the announcement box since I'm seeing some empty ones. I'll create a separate issue for that though.

**Comment by kodehammer** [comment]
done
