### ISSUE TITLE
Home page items

### ISSUE THREAD

**Issue by mdchappe** [mdchappe/kronosource#38]
So... Let's get Armando's home page text in where it says "What is Kronosource".
Let's also remove the "Who uses kronosource" and "frequently asked questions". I'm cool with the "Simple", "efficient" and "affordable" sections as long as we remove the dummy lorem ipsum.

I plan to set up another demo with Armando to show him what the homepage COULD look like with all these additional sections... But for initial launch, let's remove them.

If I'm looking at an outdated version of the home page let me know. I did just pull and confirm that what I'm seeing is the latest changes though.

**Comment by sollenne** [comment]
this is a duplicate issue. merging with #29
