### ISSUE TITLE
show requirements per property instead of per unit

### ISSUE THREAD

**Issue by sollenne** [mdchappe/kronosource#47]
This should be in the same vein of the pet policy and announcement, if it exists, it shows up, if not, it is hidden. Also it will just be added as an additional tab at the bottom the property mgmt page. assign back to me for front end work.

**Comment by kodehammer** [comment]
Added to reg form and property manage page.

**Comment by mdchappe** [comment]
Does this need styling or can we push as is? Armando is wanting this particular issue fixed before he starts showing customers. Do we have an ETA?

**Comment by mdchappe** [comment]
If this could be pushed before 1.1, that would be super. The rest can wait. Perhaps tomorrow?

**Comment by sollenne** [comment]
Styling now.

**Comment by mdchappe** [comment]
Lets go ahead and push to demo and www when complete if that's cool with y'all.

**Comment by sollenne** [comment]
Yeah zak said he would this afternoon.
