### ISSUE TITLE
Locator Accounts can't see property pics

### ISSUE THREAD

**Issue by mdchappe** [mdchappe/kronosource#55]
"Hey Matt I've noticed an issue with the site. When I upload the property pics the locator accounts can't see them. They can see the unit pics but not property ones."

**Comment by kodehammer** [comment]
Sometime between implementing the feature and launch, that portion of the viewUnit page was overwritten.  Probably some weird git merge/conflict thing.  I put it back and pushed to dev/git, it's ready for @sollenne to style before pushing to demo and live.

**Comment by mdchappe** [comment]
Yo @sollenne , can you style this brah? Armando is wanting this particular issue fixed before he starts showing customers. Do you have an ETA?

**Comment by mdchappe** [comment]
If this could be pushed before 1.1, that would be super. The rest can wait. Perhaps tomorrow?
