### ISSUE TITLE
Property Update page issues

### ISSUE THREAD

**Issue by mdchappe** [mdchappe/kronosource#60]
On the property page where the properties update their info the tabs for requirements, announcements, etc. aren't working properly. When you click on one tab the formatting gets out of whack and is glitchy. I attached a screen shot to show you what I mean. Let me know if you have any questions on it.

![image](https://f.cloud.github.com/assets/1412976/2380859/0bec24c4-a8b4-11e3-865f-ac6a2da8f4e0.png)

**Comment by sollenne** [comment]
kronos.css and kronos.js were never updated. doing that now.
