### ISSUE TITLE
/message/read "to" & "from" links

### ISSUE THREAD

**Issue by sollenne** [mdchappe/kronosource#9]
These links don't work and load an error when clicked.

**Comment by kodehammer** [comment]
Committed fix for this.

**Comment by sollenne** [comment]
Partially fixed. The link "to" probably shouldn't be a link at all. I will see about fixing that part. 
The "From" link starts a new message to the sender, but you are already on the reply page. I'm going to see if I can make a dropdown when you hover over the "from" link that will give options like. "send them a new message", and "visit profile"

**Comment by kodehammer** [comment]
Not sure what you mean about "already on the reply page".  There's only one page from which messages are sent, the message/compose function.  Clicking the reply button auto-populates some reply-specific texts.  Clicking the "from" link on my local environment takes me to the compose page with the default subject as expected.  Might consider removing the default subject, though, as it just occurred to me that using that link to initiate a new message to a locator would produce a kind of weird default subject.

Probably right about "to" not needing to be a link.

I think you're over-complicating this project considering the deadline and what we're being paid.  If we handed it over right now it's already worth way more than he's paying.  Of course, I can't tell you how to spend your free time.  I'll be handing over the bare minimum.

**Comment by sollenne** [comment]
I'm just getting into it I guess. That's why I labeled some as "enhancements" so that they don't get in the way of what's really important.

**Comment by kodehammer** [comment]
I do appreciate your enthusiasm.

I removed the link from the "to" and removed the default subject from new messages so there won't be any weirdness if a property clicks the link to initiate a new message thread with a locator.  Anything else I need to do with this one?

**Comment by sollenne** [comment]
I did some of the same things and committed already. I need to see if there are conflicts.

**Comment by sollenne** [comment]
Everything is cool with this one. Changing to "enhancement" for the dropdown I want to add. More pressing matters at hand so I'll get to this one when I can.

**Comment by sollenne** [comment]
this all seems fine.
